---
- hosts: all
  become: true
  vars:
    packages:
      - git
      - htop
      - tmux
      - vim
      
  tasks:

  - name: Install base packages using APT
    ansible.builtin.apt:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    with_items: "{{ packages }}" 
    when: ( ansible_distribution == "Debian" ) or
          ( ansible_distribution == "LMDE" ) or
          ( ansible_distribution == "Ubuntu" )

  - name: Install package epel-release YUM
    ansible.builtin.yum:
      name: epel-release
      state: present
    when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version <= "7" )

  - name: Install base packages using YUM
    ansible.builtin.yum:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    with_items: "{{ packages }}" 
    when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version <= "7" )

  - name: Install package epel-release DNF
    ansible.builtin.dnf:
      name: epel-release
      state: present
    when: ( ansible_distribution == "RedHat" ) or 
          ( ansible_distribution == "Rocky" ) or
          ( ansible_distribution == "Fedora" )

  - name: Install base packages using DNF
    ansible.builtin.dnf:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    with_items: "{{ packages }}" 
    when: ( ansible_distribution == "RedHat" ) or 
          ( ansible_distribution == "Rocky" ) or
          ( ansible_distribution == "Fedora" )
...