---
- hosts: all
  become: yes
  vars:
    packages:
      - git
      - htop
      - tmux
      - vim
  tasks:

  - name: Install base packages using APT
    ansible.builtin.apt:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    with_items: "{{ packages }}" 
    when: ( ansible_distribution == "Debian" ) or 
          ( ansible_distribution == "Ubuntu" )

  - name: Install package epel-release
    ansible.builtin.dnf:
      name: epel-release
      state: present
    when: ( ansible_distribution == "RedHat" ) or 
          ( ansible_distribution == "Rocky" ) or
          ( ansible_distribution == "CentOS" ) or
          ( ansible_distribution == "Fedora" )

  - name: Install base packages using DNF
    ansible.builtin.dnf:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    with_items: "{{ packages }}" 
    when: ( ansible_distribution == "RedHat" ) or 
          ( ansible_distribution == "Rocky" ) or
          ( ansible_distribution == "CentOS" ) or
          ( ansible_distribution == "Fedora" )
...