---
- hosts: all
  become: true

  tasks:

  - name: Install qemu guest agent using APT
    ansible.builtin.apt:
      name: qemu-guest-agent
      update_cache: yes
      state: latest
    when: ( ansible_distribution == "Debian" ) or
          ( ansible_distribution == "LMDE" ) or
          ( ansible_distribution == "Linux Mint" ) or
          ( ansible_distribution == "Pop!_OS" ) or
          ( ansible_distribution == "Ubuntu" )

  - name: Install qemu guest agent using YUM
    ansible.builtin.yum:
      name: qemu-guest-agent
      update_cache: yes
      state: latest
    when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version <= "7" )

  - name: Install qemu guest agent using DNF
    ansible.builtin.dnf:
      name: qemu-guest-agent
      update_cache: yes
      state: latest
    when: ( ansible_distribution == "RedHat" ) or 
          ( ansible_distribution == "Rocky" ) or
          ( ansible_distribution == "Fedora" )
...